# -*- coding: utf-8 -*-
"""
Created on Sun Jun 25 16:20:46 2023

@author: xinlo
"""
#%% Plots----------------------------------------------------------------------
big_fig_size = (6,10);
plt_line_width = 0.5; 
fig_font_size = 8;

#%% plot forces between purlin and mudule at joint 1113 (local system of purlin)
fig = plt.figure(figsize=big_fig_size)
ax0 = fig.add_subplot(611)
ax1 = fig.add_subplot(612)
ax2 = fig.add_subplot(613)
ax3 = fig.add_subplot(614)
ax4 = fig.add_subplot(615)
ax5 = fig.add_subplot(616)
plt.rc('xtick', labelsize=fig_font_size)    # fontsize of the tick labels
plt.rc('ytick', labelsize=fig_font_size)    # fontsize of the tick labels
ax0.tick_params(direction="in")
ax1.tick_params(direction="in")
ax2.tick_params(direction="in")
ax3.tick_params(direction="in")
ax4.tick_params(direction="in")
ax5.tick_params(direction="in")
ax0.plot(eleForces[:,0],nf1113[:,0]*0.0002248, linewidth=plt_line_width)
ax1.plot(eleForces[:,0],nf1113[:,1]*0.0002248, linewidth=plt_line_width)
ax2.plot(eleForces[:,0],nf1113[:,2]*0.0002248, linewidth=plt_line_width)
ax3.plot(eleForces[:,0],nf1113[:,3]*0.0007375623, linewidth=plt_line_width)
ax4.plot(eleForces[:,0],nf1113[:,4]*0.0007375623, linewidth=plt_line_width)
ax5.plot(eleForces[:,0],nf1113[:,5]*0.0007375623, linewidth=plt_line_width)
ax0.set_ylabel('Fx (kips)',fontsize=fig_font_size)
ax1.set_ylabel('Fy (kips)',fontsize=fig_font_size)
ax2.set_ylabel('Fz (kips)',fontsize=fig_font_size)
ax3.set_ylabel('Mx (kips*ft)',fontsize=fig_font_size)
ax4.set_ylabel('My (kips*ft)',fontsize=fig_font_size)
ax5.set_ylabel('Mz (kips*ft)',fontsize=fig_font_size)
ax5.set_xlabel('Time (s)',fontsize=fig_font_size)
plt.savefig('./Data/nodeForces1113.tif', transparent=False, bbox_inches='tight', dpi=200)

#%% plot displacements at joint 1113 (global system)
fig = plt.figure(figsize=big_fig_size)
ax0 = fig.add_subplot(611)
ax1 = fig.add_subplot(612)
ax2 = fig.add_subplot(613)
ax3 = fig.add_subplot(614)
ax4 = fig.add_subplot(615)
ax5 = fig.add_subplot(616)
plt.rc('xtick', labelsize=fig_font_size)    # fontsize of the tick labels
plt.rc('ytick', labelsize=fig_font_size)    # fontsize of the tick labels
ax0.tick_params(direction="in")
ax1.tick_params(direction="in")
ax2.tick_params(direction="in")
ax3.tick_params(direction="in")
ax4.tick_params(direction="in")
ax5.tick_params(direction="in")
ax0.plot(nodeDisps[:,0],nd1113[:,0]*39.3701, linewidth=plt_line_width)
ax1.plot(nodeDisps[:,0],nd1113[:,1]*39.3701, linewidth=plt_line_width)
ax2.plot(nodeDisps[:,0],nd1113[:,2]*39.3701, linewidth=plt_line_width)
ax3.plot(nodeDisps[:,0],nd1113[:,3], linewidth=plt_line_width)
ax4.plot(nodeDisps[:,0],nd1113[:,4], linewidth=plt_line_width)
ax5.plot(nodeDisps[:,0],nd1113[:,5], linewidth=plt_line_width)
ax0.set_ylabel('dX (in)',fontsize=fig_font_size)
ax1.set_ylabel('dY (in)',fontsize=fig_font_size)
ax2.set_ylabel('dZ (in)',fontsize=fig_font_size)
ax3.set_ylabel('rX (rad)',fontsize=fig_font_size)
ax4.set_ylabel('rY (rad)',fontsize=fig_font_size)
ax5.set_ylabel('rZ (rad)',fontsize=fig_font_size)
ax5.set_xlabel('Time (s)',fontsize=fig_font_size)
plt.savefig('./Data/nodeDisp1113.tif', transparent=False, bbox_inches='tight', dpi=200)

#%% plot y displacements at joint 1113 (local system of purlin)
fig = plt.figure(figsize=(6,10))
ax0 = fig.add_subplot(611)
ax1 = fig.add_subplot(612)
ax2 = fig.add_subplot(613)
ax3 = fig.add_subplot(614)
ax4 = fig.add_subplot(615)
ax5 = fig.add_subplot(616)
plt.rc('xtick', labelsize=fig_font_size)    # fontsize of the tick labels
plt.rc('ytick', labelsize=fig_font_size)    # fontsize of the tick labels
ax0.tick_params(direction="in")
ax1.tick_params(direction="in")
ax2.tick_params(direction="in")
ax3.tick_params(direction="in")
ax4.tick_params(direction="in")
ax5.tick_params(direction="in")
ax0.plot(nodeDisps[:,0],nd1013LocY*39.3701, linewidth=plt_line_width)
ax1.plot(nodeDisps[:,0],nd1813LocY*39.3701, linewidth=plt_line_width)
ax2.plot(nodeDisps[:,0],nd1113LocY*39.3701, linewidth=plt_line_width)
ax3.plot(nodeDisps[:,0],nd1813m1013LocY*39.3701, linewidth=plt_line_width)
ax4.plot(nodeDisps[:,0],nd1813m1113LocY*39.3701, linewidth=plt_line_width)
ax5.plot(nodeDisps[:,0],nd1013m1113LocY*39.3701, linewidth=plt_line_width)
ax0.set_ylabel('N1013 (in)',fontsize=fig_font_size)
ax1.set_ylabel('N1813 (in)',fontsize=fig_font_size)
ax2.set_ylabel('N1113 (in)',fontsize=fig_font_size)
ax3.set_ylabel('N1813 - N1013 (in)',fontsize=fig_font_size)
ax4.set_ylabel('N1813 - N1113 (in)',fontsize=fig_font_size)
ax5.set_ylabel('N1013 - N1113 (in)',fontsize=fig_font_size)
ax5.set_xlabel('Time (s)',fontsize=fig_font_size)
plt.savefig('./Data/nodeDisp1013to1113LocY.tif', transparent=False, bbox_inches='tight', dpi=200)